[build-system]
requires = ["setuptools>=69.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scraper-engine"
version = "0.1.0"
description = "Engine riutilizzabile per scraping, fetching, parsing, logging e storage"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Alessandro Ciapetti" }]
dependencies = [
    "curl-cffi>=0.15.0",
    "extruct>=0.18.0",
    "pyyaml>=6.0.3",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = [
    "scraper_engine",
    "scraper_engine.fetchers",
    "scraper_engine.handlers",
    "scraper_engine.loggers",
    "scraper_engine.loggers.configs",
    "scraper_engine.parsers",
    "scraper_engine.storage",
]

[tool.setuptools.package-data]
scraper_engine = ["loggers/*.yaml"]
