[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mio-package"
version = "0.1.0"
description = "Il mio package riutilizzabile"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Tuo Nome" }
]
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
scraper_engine = ["loggers/*.yaml"]


[tool.ruff]
line-length = 99
target-version = "py311"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"


[tool.ruff.lint.pydocstyle]
convention = "google"  

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # bugbear
    "PL",  # pylint (subset)
    "UP",  # pyupgrade
    "D",   # pydocstyle
    "C90", # mccabe complexity
    "N",   # pep8-naming
    "W",   # pycodestyle warnings
    "S",   # bandit security
    "A",   # flake8-builtins
    "RUF", # ruff-specific
]

ignore = [
    "PLR2004",  # magic values
    "PLR0913",  # troppi argomenti
    # "PLR0912"   # troppi branch
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true


[tool.mypy]
python_version = "3.11"
install_types = true
explicit_package_bases = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
